[package]
name = "dilbert"
version = "0.1.0"
edition = "2021"
authors = ["Cameron Kerr <cameron.kerr.nz@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
